### PR TITLE
Home page casey

### PR DESCRIPTION
**Pull request by Casey-Forsyth**

### CODE REVIEW

**Comment by yuriydyrenko** [comment]
For trip objects, the user should be the user's ID, the names are not unique. It should probably be renamed to userID

I'm not sure if we should merge this because there was Will's and Michael's trip view page which looked good

Otherwise looks good

**Comment by James-Firth** [comment]
Casey and I tried to merge this together to preserve the trip view page that Will and Michael worked on, can someone take a look at why it's failing? We can't figure it out at the moment.

**Comment by yuriydyrenko** [comment]
Locally those two tests pass but this tests fails:
Trip Controller GET /trips/:id should list trip item ids:

Also the user is still a user name not id

**Comment by James-Firth** [comment]
Oh I think I might see the problem, I'll push a potential fix and see if it builds (My VM died so I can't run a local test right now :( )

**Comment by James-Firth** [comment]
Casey and I didn't manage to the userID working but wanted to get everything else pulled.

Also it seems the tests pass now, should I merge?

**Pull request merged**
